import { Product } from './product';


export const PRODUCTS : Product[] = [
  {
    id : 105,
    name : "Infix S5",
    price : 9599,
    url : "../assets/images/Mobiles/infinix-s5-x652-original-imafh8nfjgzb7wug.jpeg",
    description : "Add a touch of glamor and style to your lifestyle by getting the Infinix S5 smartphone. This phone’s punch-hole display features a large screen size of 16.76 cm (6.6), which is sure to offer a larger and more immersive visual experience. This HD+ smartphone comes with a 16 MP AI quad-camera at the back so you can capture amazing pictures at all times and a 32 MP in-display selfie camera to capture captivating selfies. The large battery capacity of 4000 mAh, with AI power management, helps you go for almost two days on a full charge.",
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 106,
    name: "Lenovo K10",
    price: 699,
    url : "../assets/images/Mobiles/lenovo-k10-note-pafr0026in-original-imafkyarhbp9dqxk.jpeg",
    description: "A great phone with one of the best cameras",
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],

  },
  {
    id : 107,
    name: "Redmi 8A",
    price: 299,
    url : "../assets/images/Mobiles/mi-redmi-8a-mzb8459in-original-imafkmg2mza82yyu.jpeg",
    description: "",
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 108,
    name: "Moto G8 Plus",
    price: 399,
    url : "../assets/images/Mobiles/moto-g8-plus-64-a-page0005in-motorola-4-original-imafhgnadmgdqh6u.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],

  },
  {
    id : 108,
    name: "Moto 4",
    price: 349,
    url : "../assets/images/Mobiles/na-128-a-pafb0023in-motorola-4-original-imafhmzvrhbrzs5c.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 109,
    name: "Nokia 7.2",
    price: 499,
    url : "../assets/images/Mobiles/nokia-7-2-ta-1193-ds-original-imafkjay3kuxhccp.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 110,
    name: "Oppo Reno 2Z",
    price: 399,
    url : "../assets/images/Mobiles/oppo-reno-2z-cph1945-original-imafjv59buhc9qyw.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 120,
    name: "Oppo Reno 3",
    price: 499,
    url : "../assets/images/Mobiles/oppo-reno3-pro-cph2035-original-imafpj4fpqp3zpq3.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 130,
    name: "Realme 5 Pro",
    price: 599,
    url : "../assets/images/Mobiles/realme-5-pro-rmx1971-original-imafjhk3dyggb2bg.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 140,
    name: "Realme X2 Pro",
    price: 549,
    url : "../assets/images/Mobiles/realme-x2-pro-rmx1931-original-imafmf597chy5p8u.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 150,
    name: "Samsung Galaxy A51",
    price: 649,
    url : "../assets/images/Mobiles/samsung-galaxy-a51-sm-a515fzbhins-original-imafzhr4cqc4wqnf.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 160,
    name: "Samsung Galaxy A71",
    price: 499,
    url : "../assets/images/Mobiles/samsung-galaxy-a71-sm-a715fzbwins-original-imafzvtqvz7vtgzs.jpeg",
    description: '',
    category : "Mobiles",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 201 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 202 ,
    name : "Acer Laptop",
    price : 499,
    url : "../assets/images/Laptops/acer-original-imafpdyeeyndtnn3.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  }
  ,{
    id : 203 ,
    name : "Apple MacBook",
    price : 899,
    url : "../assets/images/Laptops/apple-na-thin-and-light-laptop-original-imafe6f78hur4jbh.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 204 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 201 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 201 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 201 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 201 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 201 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 201 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ],
  },
  {
    id : 201 ,
    name : "Acer Gaming laptop",
    price : 599,
    url : "../assets/images/Laptops/acer-na-gaming-laptop-original-imafs5prytwgrcyf.jpeg" ,
    description : "",
    category : "Laptops",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ]
  },
  {
    id : 301 ,
    name : "LG 43 inch",
    price : 999,
    url : "../assets/images/TV/lg-43um7290ptf-original-imafq6yp8fagh25s.jpeg" ,
    description : "",
    category : "TV",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ]
  },
  {
    id : 301 ,
    name : "LG 43 inch",
    price : 999,
    url : "../assets/images/TV/lg-43um7290ptf-original-imafq6yp8fagh25s.jpeg" ,
    description : "",
    category : "TV",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ]
  },
  {
    id : 301 ,
    name : "LG 43 inch",
    price : 999,
    url : "../assets/images/TV/lg-43um7290ptf-original-imafq6yp8fagh25s.jpeg" ,
    description : "",
    category : "TV",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ]
  },
  {
    id : 301 ,
    name : "LG 43 inch",
    price : 999,
    url : "../assets/images/TV/lg-43um7290ptf-original-imafq6yp8fagh25s.jpeg" ,
    description : "",
    category : "TV",
    highlights : ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
    "16.76 cm (6.6 inch) HD+ Display",
    "16MP + 5MP + 2MP + Low Light Sensor | 32MP Front Camera",
    "4000 mAh Li-ion Polymer Battery",
    "Helio P22 (MTK6762) Processor"
    ]
  },
  {
    id : 401 ,
    name : "Whirlpool 190 L Direct Cool Single Door 4 Star",
    price : 1299,
    url : "../assets/images/Refrigerators/sapphire-radiance-4-whirlpool-original-imafgw6zqv49txut.jpeg" ,
    description : "This Whirlpool Refrigerator makes use of the 6th Sense QuickCool technology to ensure cooling retention for up to nine hours. This way, when the power goes out, you can still enjoy chilled beverages and ice creams. Equipped with Toughened Glass Shelves, you can store large containers of food without causing any damage to the appliance.",
    category : "Refrigerator",
    highlights : ["190 L : Good for couples and small families",
      "DC Inverter Compressor",
      "4 Star : For Energy savings up to 45%",
      "Direct Cool : Economical, consumes less electricity, requires manual defrosting"
    ]
  },
  {
    id : 401 ,
    name : "Whirlpool 190 L Direct Cool Single Door 4 Star",
    price : 1299,
    url : "../assets/images/Refrigerators/sapphire-radiance-4-whirlpool-original-imafgw6zqv49txut.jpeg" ,
    description : "This Whirlpool Refrigerator makes use of the 6th Sense QuickCool technology to ensure cooling retention for up to nine hours. This way, when the power goes out, you can still enjoy chilled beverages and ice creams. Equipped with Toughened Glass Shelves, you can store large containers of food without causing any damage to the appliance.",
    category : "Refrigerator",
    highlights : ["190 L : Good for couples and small families",
      "DC Inverter Compressor",
      "4 Star : For Energy savings up to 45%",
      "Direct Cool : Economical, consumes less electricity, requires manual defrosting"
    ]
  },
  {
    id : 401 ,
    name : "Whirlpool 190 L Direct Cool Single Door 4 Star",
    price : 1299,
    url : "../assets/images/Refrigerators/sapphire-radiance-4-whirlpool-original-imafgw6zqv49txut.jpeg" ,
    description : "This Whirlpool Refrigerator makes use of the 6th Sense QuickCool technology to ensure cooling retention for up to nine hours. This way, when the power goes out, you can still enjoy chilled beverages and ice creams. Equipped with Toughened Glass Shelves, you can store large containers of food without causing any damage to the appliance.",
    category : "Refrigerator",
    highlights : ["190 L : Good for couples and small families",
      "DC Inverter Compressor",
      "4 Star : For Energy savings up to 45%",
      "Direct Cool : Economical, consumes less electricity, requires manual defrosting"
    ]
  },
  {
    id : 401 ,
    name : "Whirlpool 190 L Direct Cool Single Door 4 Star",
    price : 1299,
    url : "../assets/images/Refrigerators/sapphire-radiance-4-whirlpool-original-imafgw6zqv49txut.jpeg" ,
    description : "This Whirlpool Refrigerator makes use of the 6th Sense QuickCool technology to ensure cooling retention for up to nine hours. This way, when the power goes out, you can still enjoy chilled beverages and ice creams. Equipped with Toughened Glass Shelves, you can store large containers of food without causing any damage to the appliance.",
    category : "Refrigerator",
    highlights : ["190 L : Good for couples and small families",
      "DC Inverter Compressor",
      "4 Star : For Energy savings up to 45%",
      "Direct Cool : Economical, consumes less electricity, requires manual defrosting"
    ]
  }

];

